(with (map budan dango human human-node budan-node dango-node conv)
	  (set! map ("MapGet" "data/map1"))
	  (set! budan ("SimpleSpriteGet" "data/budan.sprite"))
	  (set! dango ("SimpleSpriteGet" "data/dango.sprite"))
	  (set! human ("SimpleSpriteGet" "data/human1.sprite"))
	  (set! budan-node ("SpriteAdd" map budan 32 0 0 32 32 31 31))
	  (set! dango-node ("SpriteAdd" map dango 0  0 0 32 32 31 31))
	  (set! human-node ("SpriteAdd" map human 64 32 16 32 32 31 31))
      ("NodeStateSet" budan-node 0)
      ("NodeStateSet" dango-node 0)
      ("NodeStateSet" human-node 0)
	  ("CurrentMapSet" map)
	  ("ViewPointMove" -200 -200 120)
      ("DelayEventAdd" 0 120 (lambda () ("ViewPointShiver" 5)))
      (with (u d l r)
            (set! u (lambda ()
                      ("NodeStateSet" human-node 3)
                      ("NodeMove" human-node 64 32 16 120)
                      ("DelayEventAdd" 0 120 r)))
            (set! r (lambda ()
                      ("NodeStateSet" human-node 2)
                      ("NodeMove" human-node 128 32 16 120)
                      ("DelayEventAdd" 0 120 d)))
            (set! d (lambda ()
                      ("NodeStateSet" human-node 0)
                      ("NodeMove" human-node 128 72 16 120)
                      ("DelayEventAdd" 0 120 l)))
            (set! l (lambda ()
                      ("NodeStateSet" human-node 1)
                      ("NodeMove" human-node 64 72 16 120)
                      ("DelayEventAdd" 0 120 u)))
            ("DelayEventAdd" 0 120 r)
            )
	  ("NodeMove" budan-node 200 30 0 120)
	  ("DelayEventAdd" 0 60  (lambda () ("NodeMove" dango-node 150 30 0 120)))
	  (with (move-left move-right)
	  		(set! move-left (lambda ()
                              ("NodeMove" budan-node 182 30 0 30)
                              ("DelayEventAdd" 0 30 move-right)))
	  		(set! move-right (lambda ()
                               ("NodeMove" budan-node 200 30 0 30)
                               ("DelayEventAdd" 0 30 move-left)))
	    	("DelayEventAdd" 0 180 move-right))
      (set! conv ("ConversationGet" "data/conv1"))
      ("ConversationPageSet" conv 0)
      ("CurrentConversationSet" conv)
      ("TimerResume" 0)
	  )
