(with (map budan dango budan-node dango-node conv)
	  (set! map ("GetMap" "data/map1"))
	  (set! budan ("GetSimpleSprite" "data/budan.sprite"))
	  (set! dango ("GetSimpleSprite" "data/dango.sprite"))
	  (set! budan-node ("AddSpriteToMap" map budan 32 0 0 32 32 31 31))
	  (set! dango-node ("AddSpriteToMap" map dango 0  0 0 32 32 31 31)) 
	  ("SetCurrentMap" map)
	  ("SetViewPoint" 0 0)
	  ("SpriteMoveTo" budan-node 200 30 0 120)
	  ("AddDelayEvent" 0 60  (lambda () ("SpriteMoveTo" dango-node 150 30 0 120)))
	  (with (move-left move-right)
	  		(set! move-left (lambda ()
                              ("SpriteMoveTo" budan-node 182 30 0 30)
                              ("AddDelayEvent" 0 30 move-right)))
	  		(set! move-right (lambda ()
                               ("SpriteMoveTo" budan-node 200 30 0 30)
                               ("AddDelayEvent" 0 30 move-left)))
	    	("AddDelayEvent" 0 180 move-right))
      (set! conv ("GetConversation" "data/conv1"))
      ("SetConversationPage" conv 0)
      ("SetCurrentConversation" conv)
      ("ResumeTimer" 0)
	  )
