(with (map budan dango budan-node dango-node)
	  (set! map ("GetMap" "data/map1"))
	  (set! budan ("GetSimpleSprite" "data/budan.sprite"))
	  (set! dango ("GetSimpleSprite" "data/dango.sprite"))
	  (set! budan-node ("AddSpriteToMap" map budan 32 0 0 32 32 31 31))
	  (set! dango-node ("AddSpriteToMap" map dango 0  0 0 32 32 31 31)) 
	  ("SetCurrentMap" map)
	  ("SetViewPoint" 0 0)
	  ("SpriteMoveTo" budan-node 200 30 0 120)
	  ("AddTickEvent" 60  (lambda () ("SpriteMoveTo" dango-node 150 30 0 120)))
	  (with (move-left move-right)
	  		(set! move-left (lambda ()
                              ("SpriteMoveTo" budan-node 182 30 0 30)
                              ("AddTickEvent" 30 move-right)))
	  		(set! move-right (lambda ()
                               ("SpriteMoveTo" budan-node 200 30 0 30)
                               ("AddTickEvent" 30 move-left)))
			("AddTickEvent" 180 move-right))
	  )
